apiVersion: v1
kind: Service
metadata:
  name: adcash-service
  labels:
    app: adcash
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: adcash
  ports:
    - name: http
      protocol: TCP
      port: 80         
      targetPort: 8080  