####[ec2-user@ip-172-31-9-46 adcash-prometheus]$ cat adcash-prometheus-playbook.yml
---
- name: Install and run Prometheus on local VM
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Install required packages
      package:
        name:
          - wget
          - tar
          - python3
        state: present

    - name: Create prometheus user
      user:
        name: prometheus
        system: yes
        shell: /sbin/nologin

    - name: Download Prometheus 2.52.0
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symbolic link to /opt/prometheus
      file:
        src: /opt/prometheus-2.52.0.linux-amd64
        dest: /opt/prometheus
        state: link

    - name: Create Prometheus config file
      copy:
        dest: /opt/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'adcash-app'
              static_configs:
                - targets: ['13.232.9.68:80']

    - name: Run Prometheus in background
      shell: |
        nohup /opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --web.listen-address=":9090" > /var/log/prometheus.log 2>&1 &
      args:
        executable: /bin/bash
